# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\temp.proto\"D\n\nAddRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x19\n\x0bReadRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"V\n\x0cReadResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\x12\x0e\n\x06result\x18\x05 \x01(\t\"G\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\" \n\x0eUpdateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"=\n\x03\x45mp\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\x32\xbb\x01\n\x10\x45mployeesService\x12#\n\x06\x41\x64\x64\x45mp\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12&\n\x07ReadEmp\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12,\n\tUpdateEmp\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\x12,\n\tDeleteEmp\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')



_ADDREQUEST = DESCRIPTOR.message_types_by_name['AddRequest']
_ADDRESPONSE = DESCRIPTOR.message_types_by_name['AddResponse']
_READREQUEST = DESCRIPTOR.message_types_by_name['ReadRequest']
_READRESPONSE = DESCRIPTOR.message_types_by_name['ReadResponse']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['UpdateResponse']
_DELETEREQUEST = DESCRIPTOR.message_types_by_name['DeleteRequest']
_DELETERESPONSE = DESCRIPTOR.message_types_by_name['DeleteResponse']
_EMP = DESCRIPTOR.message_types_by_name['Emp']
AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:AddRequest)
  })
_sym_db.RegisterMessage(AddRequest)

AddResponse = _reflection.GeneratedProtocolMessageType('AddResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESPONSE,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:AddResponse)
  })
_sym_db.RegisterMessage(AddResponse)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

ReadResponse = _reflection.GeneratedProtocolMessageType('ReadResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:ReadResponse)
  })
_sym_db.RegisterMessage(ReadResponse)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERESPONSE,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:DeleteResponse)
  })
_sym_db.RegisterMessage(DeleteResponse)

Emp = _reflection.GeneratedProtocolMessageType('Emp', (_message.Message,), {
  'DESCRIPTOR' : _EMP,
  '__module__' : 'emp_pb2'
  # @@protoc_insertion_point(class_scope:Emp)
  })
_sym_db.RegisterMessage(Emp)

_EMPLOYEESSERVICE = DESCRIPTOR.services_by_name['EmployeesService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDREQUEST._serialized_start=13
  _ADDREQUEST._serialized_end=81
  _ADDRESPONSE._serialized_start=83
  _ADDRESPONSE._serialized_end=112
  _READREQUEST._serialized_start=114
  _READREQUEST._serialized_end=139
  _READRESPONSE._serialized_start=141
  _READRESPONSE._serialized_end=227
  _UPDATEREQUEST._serialized_start=229
  _UPDATEREQUEST._serialized_end=300
  _UPDATERESPONSE._serialized_start=302
  _UPDATERESPONSE._serialized_end=334
  _DELETEREQUEST._serialized_start=336
  _DELETEREQUEST._serialized_end=363
  _DELETERESPONSE._serialized_start=365
  _DELETERESPONSE._serialized_end=397
  _EMP._serialized_start=399
  _EMP._serialized_end=460
  _EMPLOYEESSERVICE._serialized_start=463
  _EMPLOYEESSERVICE._serialized_end=650
# @@protoc_insertion_point(module_scope)
