# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"r\n\x11\x43reateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\x12\x10\n\x08login_id\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\x1d\n\x0fReadUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"r\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\x12\x10\n\x08login_id\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x0cUserResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x10\n\x0eReadAllRequest\"e\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x05\x12\x10\n\x08login_id\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\",\n\x0fReadAllResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.user.User2\xad\x02\n\x0bUserService\x12\x39\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x12\x35\n\x08ReadUser\x12\x15.user.ReadUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nUpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12\x39\n\nDeleteUser\x12\x17.user.DeleteUserRequest\x1a\x12.user.UserResponse\x12\x36\n\x07ReadAll\x12\x14.user.ReadAllRequest\x1a\x15.user.ReadAllResponseb\x06proto3')



_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_READUSERREQUEST = DESCRIPTOR.message_types_by_name['ReadUserRequest']
_UPDATEUSERREQUEST = DESCRIPTOR.message_types_by_name['UpdateUserRequest']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteUserRequest']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_READALLREQUEST = DESCRIPTOR.message_types_by_name['ReadAllRequest']
_USER = DESCRIPTOR.message_types_by_name['User']
_READALLRESPONSE = DESCRIPTOR.message_types_by_name['ReadAllResponse']
CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

ReadUserRequest = _reflection.GeneratedProtocolMessageType('ReadUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _READUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.ReadUserRequest)
  })
_sym_db.RegisterMessage(ReadUserRequest)

UpdateUserRequest = _reflection.GeneratedProtocolMessageType('UpdateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UpdateUserRequest)
  })
_sym_db.RegisterMessage(UpdateUserRequest)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

ReadAllRequest = _reflection.GeneratedProtocolMessageType('ReadAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _READALLREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.ReadAllRequest)
  })
_sym_db.RegisterMessage(ReadAllRequest)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.User)
  })
_sym_db.RegisterMessage(User)

ReadAllResponse = _reflection.GeneratedProtocolMessageType('ReadAllResponse', (_message.Message,), {
  'DESCRIPTOR' : _READALLRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:user.ReadAllResponse)
  })
_sym_db.RegisterMessage(ReadAllResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEUSERREQUEST._serialized_start=20
  _CREATEUSERREQUEST._serialized_end=134
  _READUSERREQUEST._serialized_start=136
  _READUSERREQUEST._serialized_end=165
  _UPDATEUSERREQUEST._serialized_start=167
  _UPDATEUSERREQUEST._serialized_end=281
  _DELETEUSERREQUEST._serialized_start=283
  _DELETEUSERREQUEST._serialized_end=314
  _USERRESPONSE._serialized_start=316
  _USERRESPONSE._serialized_end=361
  _READALLREQUEST._serialized_start=363
  _READALLREQUEST._serialized_end=379
  _USER._serialized_start=381
  _USER._serialized_end=482
  _READALLRESPONSE._serialized_start=484
  _READALLRESPONSE._serialized_end=528
  _USERSERVICE._serialized_start=531
  _USERSERVICE._serialized_end=832
# @@protoc_insertion_point(module_scope)
