name: Run Postman Collection

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Newman and HTML Reporter 
        run: |
          npm install -g newman
          npm install -g reporter  # Install the HTML reporter globally
        shell: cmd  # Use cmd shell for compatibility

      - name: Run Newman
        run: |
          newman run Postman/User_collection.json -e Postman/User_environment.json -r htmlextra --reporter-htmlextra-export Postman/reports/newman-report.html  # Run the Postman collection with Newman and generate an HTML report
        shell: cmd  # Use cmd shell for compatibility
