name: Run Postman Collection

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the repository code
      - name: Create dire
        run : |
          mkdir TestArtifact 

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Set up Node.js
        with:
          node-version: '16.x'  # Specify the Node.js version

      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  
        shell: cmd  # Use cmd shell for compatibility

      - name: Verify Installation
        run: |
          npm list -g --depth=0  
        shell: cmd  # Use cmd shell for compatibility

      - name: Run Newman
        run: |
          newman run Postman/User_collection.json -e Postman/User_environment.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html 
      - name: reports 
        uses: actions/upload-artifact@v3  
        with :
          name: Report
          path: testArtifacts
