name: Run Postman Collection

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          mkdir postman/reports

    
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install Newman and HTML Reporter 
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra  # Install the HTML reporter globally

      - name: Run Newman
        run: |
          newman run postman/User_collection.json -e postman/User_environment.json --reporters cli,html --reporter-html-export postman/reports/newman-report.html  # Run the Postman collection with Newman and generate an HTML report
      - name: Publish Report
        uses : actions/upload-artifact@v2
        with :
          name : Reports
          path : postman/reports
